---
sidebar: sidebar
permalink: callhome-arw-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: callhome.arw events
---

= callhome.arw events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== callhome.arw.activity.seen
*Severity*::
ALERT
*Description*::
This message occurs when ransomware activity is detected. To protect the data, a Snapshot copy has been created, which can be used to restore the original data. If your system is configured to do so, it generates and transmits an AutoSupport (or "call home") message to NetApp technical support and to the configured destinations. Successful delivery of an AutoSupport message significantly improves problem determination and resolution.
*Corrective Action*::
Refer to the anti-ransomware documentation to take remedial measures for ransomare activity. If you need assistance, contact NetApp technical support.
*Syslog Message*::
Call-home message for %s
*Parameters*::
*subject* (STRING): AutoSupport subject or title for this event.
*volName* (STRING): Name of the volume.
*volUuid* (STRING): UUID of the volume.
*vserverName* (STRING): Name of the Vserver.
*vserverUuid* (STRING): UUID of the Vserver.
