---
sidebar: sidebar
permalink: dbs-ekm-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: dbs.ekm events
---

= dbs.ekm events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== dbs.ekm.cert.alert
*Severity*::
ALERT
*Description*::
This message occurs when Distributed Block Store (DBS) detects that an External Key Management (EKM) key server configuration contains a certificate that will expire in less than 7 days.
*Corrective Action*::
Renew each listed certificate and update the associated EKM key server configuration.
*Syslog Message*::
DBS has detected that an EKM key server certificate is nearing expiration. Cluster fault type %s, fault ID %u, status %u. %s
*Parameters*::
*cfType* (STRING): DBS cluster fault type of the associated object.
*cfID* (INT): DBS cluster fault ID number associated with the fault.
*cfStatus* (INT): Current status of the cluster fault. 1 = New (just reported), 2 = Existing (updated), 3 = Resolved (closed).
*cfDetails* (STRING): Details of the certificates that are nearing expiration.
*cfExtSrc* (STRING): DBS cluster fault externalSource label created by the "CreateClusterFault" API command and attached to the fault for testing purposes.

== dbs.ekm.cert.error
*Severity*::
ERROR
*Description*::
This message occurs when Distributed Block Store (DBS) detects that an External Key Management (EKM) key server configuration contains a certificate that will expire in less than 30 days.
*Corrective Action*::
Renew each listed certificate and update the associated EKM key server configuration.
*Syslog Message*::
DBS has detected that an EKM key server certificate is nearing expiration. Cluster fault type %s, fault ID %u, status %u. %s
*Parameters*::
*cfType* (STRING): DBS cluster fault type of the associated object.
*cfID* (INT): DBS cluster fault ID number associated with the fault.
*cfStatus* (INT): Current status of the cluster fault. 1 = New (just reported), 2 = Existing (updated), 3 = Resolved (closed).
*cfDetails* (STRING): Details of the certificates that are nearing expiration.
*cfExtSrc* (STRING): DBS cluster fault externalSource label created by the "CreateClusterFault" API command and attached to the fault for testing purposes.
