---
sidebar: sidebar
permalink: dbs-disconn-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: dbs.disconn events
---

= dbs.disconn events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== dbs.disconn.cluster.pair
*Severity*::
ERROR
*Description*::
This message occurs when the distributed block store detects that a cluster pair is disconnected or configured incorrectly. The distibuted block store is responsible for managing the data that backs the flexible volumes.
*Corrective Action*::
Check network connectivity between clusters. One of the clusters in the pair might have become misconfigured or disconnected. Remove the local pairing and retry pairing the clusters.
*Syslog Message*::
The distributed block store detects that the cluster pair is disconnected or configured incorrectly. The cluster fault type is %s and fault id is %u.
*Parameters*::
*cfType* (STRING): Distibuted block store cluster fault type of the associated object.
*cfID* (INT): Distibuted block store cluster fault ID number associated with the fault.
*cfStatus* (INT): Current status of the cluster fault. 1 = New (just reported), 2 = Existing (updated), 3 = Resolved (closed).
*cfDetails* (STRING): Description of the cluster fault, including context details.
*cfExtSrc* (STRING): Distibuted block store cluster fault external source label created by the "CreateClusterFault" API command and attached to the fault for testing purposes.

== dbs.disconn.remote.node
*Severity*::
ERROR
*Description*::
This message occurs when the Distributed Block Store (DBS) detects that a remote node is not connected to cluster network. The DBS is responsible for managing the data that backs the FlexVols(R).
*Corrective Action*::
Ping the remote nodes using jumbo frames to test network connectivity.
*Syslog Message*::
The Distributed Block Store has detected that a remote node is not connected to cluster network. The cluster fault type is %s and fault id is %u.
*Parameters*::
*cfType* (STRING): DBS cluster fault type of the associated object.
*cfID* (INT): DBS cluster fault ID number associated with the fault.
*cfStatus* (INT): Current status of the cluster fault. 1 = New (just reported), 2 = Existing (updated), 3 = Resolved (closed).
*cfDetails* (STRING): Description of the cluster fault, including context details.
*cfExtSrc* (STRING): DBS cluster fault externalSource label created by the CreateClusterFault API command and attached to the fault for testing purposes.
