---
sidebar: sidebar
permalink: dbs-volumes-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: dbs.volumes events
---

= dbs.volumes events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== dbs.volumes.degraded
*Severity*::
ALERT
*Description*::
This message occurs when the distributed block store detects that the listed volumes currently have only one copy of some of their data (they do not have a live secondary). This normally happens when a primary or live secondary slice service experiences remote procedure call (RPC) message timeouts to a peer slice service and changes it to a dead secondary. It can also happen briefly when a volume is created. The volume is current, syncing to a live secondary. The distibuted block store is responsible for managing the data that backs the flexible volumes.
*Corrective Action*::
Check for network connectivity issues and hardware errors. There should be other faults if specific hardware components have failed. This fault clears when syncing completes and there is a live secondary slice service.
*Syslog Message*::
The distributed block store detects that the listed volumes currently have only one copy of some of their data (they do not have a live secondary). The cluster fault type is %s and fault id is %u.
*Parameters*::
*cfType* (STRING): Distibuted block store cluster fault type of the associated object.
*cfID* (INT): Distibuted block store cluster fault ID number associated with the fault.
*cfStatus* (INT): Current status of the cluster fault. 1 = New (just reported), 2 = Existing (updated), 3 = Resolved (closed).
*cfDetails* (STRING): Description of the cluster fault, including context details.
*cfExtSrc* (STRING): Distibuted block store cluster fault external source label created by the "CreateClusterFault" API command and attached to the fault for testing purposes.
