---
sidebar: sidebar
permalink: dbs-capacity-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: dbs.capacity events
---

= dbs.capacity events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== dbs.capacity.stranded
*Severity*::
NOTICE
*Description*::
This message occurs when the Distributed Block Store (DBS) detects that more than half of the cluster capacity is available on only one node. To achieve high availability (HA), the DBS effectively reduces the capacity of the largest node so that some of its capacity is stranded (unusable).
*Corrective Action*::
Adjust node disk capacities so that no node exceeds the capacity of the remaining nodes in the cluster.
*Syslog Message*::
Distributed Block Store has detected stranded capacity. Cluster fault type %s, fault ID %u, status %u. %s
*Parameters*::
*cfType* (STRING): Distributed Block Store cluster fault type of the associated object.
*cfID* (INT): Distributed Block Store cluster fault ID number associated with the fault.
*cfStatus* (INT): Current status of the cluster fault: 1 = New (just reported), 2 = Existing (updated), 3 = Resolved (closed).
*cfDetails* (STRING): Description of the cluster fault, including context details.
*cfExtSrc* (STRING): Distributed Block Store cluster fault externalSource label created by the "CreateClusterFault" API command and attached to the fault for testing purposes.
