---
sidebar: sidebar
permalink: encryption-op-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: encryption.op events
---

= encryption.op events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== encryption.op.completed
*Severity*::
NOTICE
*Description*::
This message occurs when a rekey or conversion to encryption operation is completed on a volume.
*Corrective Action*::
(None).
*Syslog Message*::
%s operation is completed on the volume '%s' in Vserver '%s'.
*Parameters*::
*op* (STRING): Rekey or conversion operation.
*volumename* (STRING): Name of the volume.
*vservername* (STRING): Name of the Vserver.

== encryption.op.paused.by.user
*Severity*::
NOTICE
*Description*::
This message occurs when a rekey or conversion to encryption operation is paused as a result of an operator request.
*Corrective Action*::
(None).
*Syslog Message*::
%s operation is paused by user on the volume '%s' in Vserver '%s'.
*Parameters*::
*op* (STRING): Rekey or conversion operation.
*volumename* (STRING): Name of the volume.
*vservername* (STRING): Name of the Vserver.

== encryption.op.paused.on.err
*Severity*::
ERROR
*Description*::
This message occurs when a rekey or conversion to encryption operation is paused as a result of an error. If it is a rekey operation, volume will use two encryption keys until the rekey operation is completed. New writes and rekeyed blocks will use the new key, while the data written before the rekey start will still use the old key in the read path. If it is a conversion to encryption operation, new writes and converted blocks will use the key, while data written before conversion will not use any key in the read path. Data access continues to be possible, although performance might be degraded.
*Corrective Action*::
Determine the cause of the error by using either the "volume encryption rekey show -vserver <vserver-name> -volume <volume-name>" command or the "volume encryption conversion show -vserver <vserver-name> -volume <volume-name>" command. Correct the error. If the error was related to rekeying, continue the operation by using the "volume encryption rekey resume -vserver <vserver-name> -volume <volume-name>" command. If the error was related to conversion to encryption, continue by using the "volume encryption conversion resume -vserver < vserver-name> -volume <volume-name>" command.
*Syslog Message*::
%s operation on volume '%s' in Vserver '%s' is paused due to an error. Reason '%s'.
*Parameters*::
*op* (STRING): Rekey or conversion operation.
*volumename* (STRING): Name of the volume.
*vservername* (STRING): Name of the Vserver.
*reason* (STRING): Reason for the failure.

== encryption.op.queued
*Severity*::
NOTICE
*Description*::
This message occurs when a plaintext volume is queued for encryption.
*Corrective Action*::
(None).
*Syslog Message*::
Volume %s in Vserver %s is queued for %s.
*Parameters*::
*volumename* (STRING): Name of the volume.
*vservername* (STRING): Name of the Vserver.
*op* (STRING): Conversion operation.

== encryption.op.started
*Severity*::
NOTICE
*Description*::
This message occurs when a rekey or conversion to encryption operation is started on a volume.
*Corrective Action*::
(None).
*Syslog Message*::
%s operation is started on the volume '%s' in Vserver '%s'.
*Parameters*::
*op* (STRING): Rekey or conversion operation.
*volumename* (STRING): Name of the volume.
*vservername* (STRING): Name of the Vserver.
