---
sidebar: sidebar
permalink: mgmtgwd-snapshot-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: mgmtgwd.snapshot events
---

= mgmtgwd.snapshot events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== mgmtgwd.snapshot.deleteWarn
*Deprecated*::
Deprecated as of Data ONTAP 9.6 because Infinite Volumes no longer exist.
*Severity*::
NOTICE
*Description*::
This message occurs when a Snapshot(tm) copy cannot be deleted from an Infinite Volume.
*Corrective Action*::
Delete one or more older Snapshot copies associated with this schedule by using the "volume snapshot delete" command.
*Syslog Message*::
Skipping deletion of scheduled Snapshot copy "%s" on volume "%s" on Vserver "%s" for schedule "%s" prefix "%s" (reason: %s).
*Parameters*::
*snapshotName* (STRING): Name of the Snapshot copy.
*volumeName* (STRING): Name of the volume.
*vserverName* (STRING): Name of the Vserver.
*scheduleName* (STRING): Name of the Snapshot policy schedule.
*prefixName* (STRING): Name of the prefix associated with the Snapshot policy schedule.
*reason* (STRING): Reason for the failure.

== mgmtgwd.snapshot.frcRestore
*Deprecated*::
Deprecated as of Data ONTAP 9.6 because Infinite Volumes no longer exist.
*Severity*::
INFORMATIONAL
*Description*::
This message occurs when a Snapshot(tm) copy is restored on an Infinite Volume using the 'force' option.
*Corrective Action*::
(None).
*Syslog Message*::
Volume '%s' on Vserver '%s' was restored to Snapshot copy '%s' using the 'force' option.
*Parameters*::
*volumeName* (STRING): Name of the volume.
*vserverName* (STRING): Name of the Vserver.
*snapshotName* (STRING): Name of the Snapshot copy.

== mgmtgwd.snapshot.partCreate
*Deprecated*::
Deprecated as of Data ONTAP 9.6 because Infinite Volumes no longer exist.
*Severity*::
ERROR
*Description*::
This message occurs when a Snapshot(tm) copy is partially created on an Infinite Volume. Residual Snapshot copies might remain on one or more Infinite Volume constituent volumes. These Snapshot copies might consume the Snapshot reserve on the constituent volumes.
*Corrective Action*::
Contact NetApp technical support.
*Syslog Message*::
Scheduled Snapshot copy '%s' of volume '%s' on Vserver '%s' for schedule '%s' prefix '%s' was partially created and cleanup failed on one or more constituent volumes.
*Parameters*::
*snapshotName* (STRING): Name of the Snapshot copy.
*volumeName* (STRING): Name of the volume.
*vserverName* (STRING): Name of the Vserver.
*scheduleName* (STRING): Name of the Snapshot policy schedule.
*prefixName* (STRING): Name of the prefix associated with the Snapshot policy schedule.
*constituentMsidList* (STRING): List of master data set IDs (MSIDs) of Infinite Volume constituent volumes that might have residual Snapshot copies.

== mgmtgwd.snapshot.tooManySnap
*Deprecated*::
Deprecated as of Data ONTAP 9.6 because Infinite Volumes no longer exist.
*Severity*::
ERROR
*Description*::
This message occurs when a Snapshot(tm) copy cannot be created on an Infinite Volume because too many Snapshot copies exist for the associated schedule.
*Corrective Action*::
Delete an older Snapshot copy associated with this schedule using the 'volume snapshot delete' command.
*Syslog Message*::
Scheduled Snapshot copy '%s' of volume '%s' on Vserver '%s' could not be created because too many Snapshot copies exist for the associated schedule.
*Parameters*::
*snapshotName* (STRING): Name of the Snapshot copy.
*volumeName* (STRING): Name of the volume.
*vserverName* (STRING): Name of the Vserver.
