---
sidebar: sidebar
permalink: sm-c2c-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: sm.c2c events
---

= sm.c2c events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== sm.c2c.rebaseline.xfer
*Severity*::
INFORMATIONAL
*Description*::
This message occurs when SnapMirror(R) performs a SnapMirror Cloud rebaseline transfer because certain conditions for an incremental transfer haven't been met between the source volume and the object-store destination endpoint of the transfer.
*Corrective Action*::
(None).
*Syslog Message*::
This will be a rebaseline transfer because certain conditions for an incremental transfer haven't been met between the source volume '%s' and the destination object-store endpoint '%s', with endpoint uuid '%s', and relationship uuid '%s'. Refer to the sktrace logs for additional details on which conditions haven't been met.
*Parameters*::
*src_path* (STRING): Path name of the source volume of the SnapMirror relationship.
*dst_ep_path* (STRING): Path name of the destination object-store endpoint of the SnapMirror relationship.
*dst_ep_uuid* (STRING): UUID of the destination object-store endpoint of the SnapMirror relationship.
*rel_uuid* (STRING): UUID of the SnapMirror relationship.

== sm.c2c.xfer.fail.no.com.snap
*Severity*::
ERROR
*Description*::
This message occurs when a SnapMirror(R) Cloud transfer fails because there is no common Snapshot(tm) copy between the source volume and the object-store destination endpoint of the transfer.
*Corrective Action*::
Retry the transfer by passing a specific Snapshot copy name using the "-s" option. Note that once you choose to go ahead with that option, you will not be able to transfer Snapshot copies older than the specified Snapshot copy. So it is suggested to select a Snapshot copy that is older than the Snapshot copies that you would like to be backed up per schedule.
*Syslog Message*::
There is no common Snapshot copy between the source volume '%s' and the destination object-store endpoint '%s', with endpoint uuid '%s', and relationship uuid '%s'.
*Parameters*::
*src_path* (STRING): Path name of the source volume of the SnapMirror relationship.
*dst_ep_path* (STRING): Path name of the destination object-store endpoint of the SnapMirror relationship.
*dst_ep_uuid* (STRING): UUID of the destination object-store endpoint of the SnapMirror relationship.
*rel_uuid* (STRING): UUID of the SnapMirror relationship.
