---
sidebar: sidebar
permalink: sms-fanout-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: sms.fanout events
---

= sms.fanout events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== sms.fanout.comm.snap.deleted
*Severity*::
ALERT
*Description*::
This message occurs when an older Snapshot(tm) copy is deleted as part of a SnapMirror(R) Synchronous resynchronize or update (common Snapshot copy) operation, which could lead to a "no common Snapshot scenario" between the synchronous and asynchronous disaster recovery (DR) copies that share the same source volume. If there is no common Snapshot copy between the synchronous and asynchronous DR copies, then a re-baseline will need to be performed during a disaster recovery.
*Corrective Action*::
You can ignore this message if there is no asynchronous relationship configured for the synchronous source volume. If there is an asynchronous relationship configured, then update the asynchronous relationship by using the "snapmirror update" command. The SnapMirror update operation will transfer the Snapshot copies that will act as common Snapshot copies between the synchronous and asynchronous destinations.
*Syslog Message*::
SnapMirror Synchronous operation '%s' for relationship '%s' has cleaned up some of the old base Snapshot copies between the synchronous source and synchronous destination, which could result in no common Snapshot copy existing between the synchronous and asynchronous destinations.
*Parameters*::
*sm_operation* (STRING): SnapMirror Synchronous operation.
*relationship_id* (STRING): Relationship UUID.
