---
sidebar: sidebar
permalink: upgrademgr-update-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: upgrademgr.update events
---

= upgrademgr.update events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== upgrademgr.update.cancelled
*Severity*::
INFORMATIONAL
*Description*::
This message occurs when the automated update of the cluster is canceled by the operator.
*Corrective Action*::
(None).
*Syslog Message*::
The automated update of the cluster has been canceled by the operator.
*Parameters*::
(None).

== upgrademgr.update.completed
*Severity*::
INFORMATIONAL
*Description*::
This message occurs when the automated update of the cluster is complete.
*Corrective Action*::
(None).
*Syslog Message*::
The automated update of the cluster is complete.
*Parameters*::
(None).

== upgrademgr.update.pausedErr
*Severity*::
ERROR
*Description*::
This message occurs when the automated update of the cluster is paused as a result of an error.
*Corrective Action*::
The automated update of the cluster has been paused due to the following reason: %s. Correct the cause of the error, and then issue the "cluster image resume-update" command to continue the automated update of the cluster.
*Syslog Message*::
The automated update of the cluster has been paused due to the following reason: %s
*Parameters*::
*pausedSummary* (STRING): Summary of the event causing the paused update.

== upgrademgr.update.pausedUser
*Severity*::
INFORMATIONAL
*Description*::
This message occurs when the automated update of the cluster is paused as a result of an operator request.
*Corrective Action*::
Issue the "cluster image resume-update" command to continue the automated update of the cluster.
*Syslog Message*::
The automated update of the cluster has been paused due to a request by the operator.
*Parameters*::
(None).

== upgrademgr.update.resumed
*Severity*::
INFORMATIONAL
*Description*::
This message occurs when the automated update of the cluster is resumed from the paused state.
*Corrective Action*::
(None).
*Syslog Message*::
The automated update of the cluster has been resumed by the operator.
*Parameters*::
(None).

== upgrademgr.update.started
*Severity*::
INFORMATIONAL
*Description*::
This message occurs when the upgrade manager begins an automated update of the cluster.
*Corrective Action*::
(None).
*Syslog Message*::
An automated update of the cluster has been started.
*Parameters*::
(None).
