---
sidebar: sidebar
permalink: wafl-maxdirsize-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: wafl.maxdirsize events
---

= wafl.maxdirsize events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== wafl.maxdirsize.boot.notice
*Severity*::
NOTICE
*Description*::
This event occurs for each volume that has a maxdirsize greater than the default during boot.
*Corrective Action*::
Use (privilege:advanced) option "volume modify -volume vol_name -maxdir-size new_value" to set the volume's maxdirsize to the default maxdirsize. However, doing so could impact system performance. If you need to increase the maximum directory size, work with technical support.
*Syslog Message*::
%s%s%s%s: This volume's maxdirsize (%uKB) is higher than the default (%uKB). There may be a performance penalty when doing operations on large directories.
*Parameters*::
*owner* (STRING): The volume owner
*vol* (STRING): The volume name
*app* (STRING): Application UUID.
*volident* (STRING): Unique identifier of the volume when the volume name alone is insufficient.
*current_maxdirsize* (INT): Default maximum directory size value.
*default_maxdirsize* (INT): Default maximum directory size value.
