---
sidebar: sidebar
permalink: wafl-snapshot_xlation_setupfailed-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: wafl.snapshot_xlation_setupfailed events
---

= wafl.snapshot_xlation_setupfailed events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== wafl.snapshot_xlation_setupfailed
*Severity*::
ERROR
*Description*::
This message occurs when WAFL(R) cannot setup the Snapshot(TM) copy translation table. Access to this Snapshot copy is disabled until the problem is resolved.
*Corrective Action*::
The Snapshot copy is inaccessible, possibly due to a resource issue.Contact NetApp technical support.
*Syslog Message*::
WAFL Snapshot copy translation table: Cannot to add entry on volume '%s%s%s' that maps physical Snapshot copy '%d' to logical Snapshot copy '%d'
*Parameters*::
*owner* (STRING): Owner of the volume.
*app* (STRING): Application UUID.
*volident* (STRING): Unique Identifier of the volume in cases where the volume name itself is insufficient.
*physical_snapid* (INT): Physical Snapshot copy index.
*Logical_snapid* (INT): Logical Snapshot copy index.
