---
sidebar: sidebar
permalink: wafl-root-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: wafl.root events
---

= wafl.root events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== wafl.root.autocreate
*Severity*::
NOTICE
*Description*::
This event is issued when no online root volume is found. It is used to indicate that auto creation of a root volume will happen.
*Corrective Action*::
(None).
*Syslog Message*::
No online root volume found on root aggregate %s. Automatically creating one.
*Parameters*::
*aggr* (STRING): The root aggregate name

== wafl.root.content.changed
*Severity*::
ERROR
*Description*::
This message occurs when the contents of the root volume are changed to those of a previous point in time. One of the following operations or events can cause the contents of the root volume to change: - The root volume is changed from the boot menu. - The nvlog is jettisoned. - The system is booted with prev_cp. - The 'wafliron -prev_cp' command is used and the changes are commited. - A SnapRestore(R) operation is done on the root volume.
*Corrective Action*::
Verify that all recent configuration changes are still in effect.
*Syslog Message*::
Contents of the root volume '%s' might have changed. Verify that all recent configuration changes are still in effect.
*Parameters*::
*vol* (STRING): Name of the root volume.

== wafl.root.create
*Severity*::
INFORMATIONAL
*Description*::
This message occurs when the system creates a root volume.
*Corrective Action*::
(None).
*Syslog Message*::
New root volume %s created.
*Parameters*::
*vol* (STRING): Name of the root volume.

== wafl.root.mark.error
*Severity*::
NOTICE
*Description*::
This event is issued when there is an error in syncing the vvol raid label of a newly created root volume.
*Corrective Action*::
(None).
*Syslog Message*::
Error setting volume %s%s as root. Changes may not be saved.
*Parameters*::
*vol* (STRING): The root volume name
*app* (STRING): Application UUID.
*volident* (STRING): To uniquely identify the volume in cases where volume name itself is insufficient.

== wafl.root.overwritesUnsafe
*Severity*::
ERROR
*Description*::
This message occurs when the root volume is not volume guaranteed or does not guarantee overwrites for space reserved files.
*Corrective Action*::
Set the Space Guarantee on the root volume to "volume" and the Fractional Reserve on the root volume to 100%.
*Syslog Message*::
Root volume %s does not protect overwrites in space reserved files.
*Parameters*::
*vol* (STRING): Root volume name.
