---
sidebar: sidebar
permalink: wafl-buf-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: wafl.buf events
---

= wafl.buf events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== wafl.buf.badHeader
*Severity*::
EMERGENCY
*Description*::
This message occurs when the system encounters a bad header in the Snapshot(tm) copy of the active map block of the filesystem.
*Corrective Action*::
Delete the bad Snapshot copy. For a SnapMirror(R) target, rebuild from source or resynchronize, after deleting the Snapshot copy. If the problem persists or if you need further assistance, contact NetApp technical support.
*Syslog Message*::
Bad header in Snapshot copy of active map in %s %s%s%s%s, Snapshot copy %d, fbn %llu.
*Parameters*::
*type* (STRING): Type of object (volume or aggregate).
*owner* (STRING): Owner of the volume.
*vol* (STRING): Name of the volume.
*app* (STRING): Application UUID.
*volident* (STRING): To uniquely identify the volume in cases where the volume name itself is insufficient.
*snapId* (INT): Snapshot(tm) copy identifier.
*fbn* (LONGINT): File block number.

== wafl.buf.freeingFreeBlock
*Severity*::
EMERGENCY
*Description*::
This message occurs when the system encounters a "freeing free block" error due to file system corruption.
*Corrective Action*::
(Call support).
*Syslog Message*::
Freeing free block at VBN %llu in %s %s%s%s%s. WAFL inconsistent. Contact NetApp technical support.
*Parameters*::
*vbn* (LONGINT): Virtual block number of the block that is freed.
*voltype* (STRING): Type of the volume.
*volowner* (STRING): Owner of the volume.
*volname* (STRING): Name of the volume (again). This is returned from WAFL_VOL_PRINT_NAME_STRINGS.
*app* (STRING): Application UUID.
*volident* (STRING): Uniquely identifies the volume in cases where the volume name itself is insufficient.
*vendor* (STRING): Name of the vendor.
